### PR TITLE
Typos and add 4.5.7 URL

### PR DESCRIPTION
**Pull request by petecooper**
@philwareham I've got some time to assist with this further - do you have a search and replace list for wiki markup to Textile?

### CODE REVIEW

**Comment by philwareham** [comment]
Hi Pete, unfortunately it's not a simple find/replace. I'm manually editing Textile in from a database dump of wiki. Each file one at a time.

**Comment by petecooper** [comment]
No worries, I had a feeling that might be the case. The ones I've added in this PR follow your style so far, as far as I can tell, so shouldn't add any additional editing burden.

**Comment by philwareham** [comment]
Great! I'll lok over these this evening when I'm near computer and merge if all ok.

**Comment by petecooper** [comment]
Just spotted all the cleanup needed from this PR - sorry, @philwareham.

**Comment by philwareham** [comment]
That's OK, easier to commit and cleanup than do it all myself from scratch, so please continue to help!

**Comment by petecooper** [comment]
You got it.

**Pull request merged**
